services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${db_name}
      MYSQL_ROOT_PASSWORD: ${root_password}
      MYSQL_USER: ${dev_user}
      MYSQL_PASSWORD: ${dev_password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data: